apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: jenkins
        image: jainankur2/loylogic:25
        ports:
        - containerPort: 80
          #      imagePullSecrets:
          #      - name: doc-registry
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80
